# Generated by Django 6.0.2 on 2026-02-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('current_price', models.FloatField(default=0)),
                ('pe_ratio', models.FloatField(null=True)),
                ('market_cap', models.FloatField(default=0)),
                ('day_change', models.FloatField(default=0)),
                ('day_change_percent', models.FloatField(default=0)),
                ('volume', models.BigIntegerField(default=0)),
                ('high_52w', models.FloatField(default=0)),
                ('low_52w', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='portfolio.portfolio')),
            ],
        ),
    ]
