# Generated by Django 6.0.2 on 2026-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='icon',
            field=models.CharField(default='📊', max_length=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_investment',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.DeleteModel(
            name='MarketSector',
        ),
    ]
